#!/bin/bash
#
# A simple script rsync when events (inotify like) on $SRC happens, using OSX
# fswatch and

# if [ "$#" -lt 2 ] || ! [ -d "$1" ]; then
if [ "$#" -lt 2 ]; then
    echo "Usage: see rsync manpage"
    exit -1;
fi

RSYNC=`which rsync`
FLAGS="-av --rsync-path=\"sudo rsync\""
SRC=${@:(-2):1} # get the second last argument as src dir

CMD="$RSYNC $FLAGS $@"

# using ANSI escape code
BLUE='\033[0;34m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
WHITE='\033[1;37m'

fswatch -0 -r $SRC --exclude="/*index.lock$"  | (
    while read -d "" EVENT; do
      echo -e "${BLUE}`date` -- ${WHITE}\"$EVENT\" -- ${YELLOW}changed."
      echo -e "${RED}Synchronizing..."
      echo -e "${GREEN}$CMD"
      eval $CMD
    done
)
