k9s:
  cluster: gke_ninth-archway-400212_us-west1-a_getvocal
  namespace:
    active: all
    lockFavorites: false
    favorites:
      - all
      - default
  view:
    active: po
  featureGates:
    nodeShell: false
  proxy: null
