#!/bin/bash

username="amine.kherbouche"
serial="arn:aws:iam::097958131044:mfa/$username"

echo "[requesting temporary credentials for $username]"

# clean the AWS env variables to avoid any conflicts
unset AWS_ACCESS_KEY_ID
unset AWS_SECRET_ACCESS_KEY
unset AWS_SESSION_TOKEN
unset AWS_SECURITY_TOKEN

aws_original_profile="${username}"
aws_ro_profile="${username}.ro"

read -r -p "Enter MFA code: " code

# get the temporary credentials for the user with read-only rights
user_credentials=$(aws sts get-session-token --serial-number "$serial" --token-code "$code" --profile "$aws_original_profile")
if [ -z "${user_credentials}" ]; then
	echo "Error: failed to get temporary credentials for $aws_original_profile" >&2
	exit 1
fi

# extract AWS secrets values from the JSON response
AWS_ACCESS_KEY_ID=$(echo "$user_credentials" | jq -r .Credentials.AccessKeyId)
AWS_SECRET_ACCESS_KEY=$(echo "$user_credentials" | jq -r .Credentials.SecretAccessKey)
AWS_SESSION_TOKEN=$(echo "$user_credentials" | jq -r .Credentials.SessionToken)

echo "export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID"
echo "export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY"
echo "export AWS_SESSION_TOKEN=$AWS_SESSION_TOKEN"

echo "[updating $aws_ro_profile in .aws/credentials]"
aws configure set aws_access_key_id "$AWS_ACCESS_KEY_ID" --profile $aws_ro_profile
aws configure set aws_secret_access_key "$AWS_SECRET_ACCESS_KEY" --profile $aws_ro_profile
aws configure set aws_session_token "$AWS_SESSION_TOKEN" --profile $aws_ro_profile
